//! FROST key generation, key shares, and key packages
const std = @import("std");
const Secp256k1 = std.crypto.ecc.Secp256k1;
const FrostError = @import("error.zig").FrostError;
const Identifier = @import("identifier.zig").Identifier;
const Signature = @import("signature.zig").Signature;
const field = @import("field.zig");
const group = @import("group.zig");
const cs = @import("ciphersuite.zig");

pub const Scalar = field.Scalar;
pub const Element = group.Element;

/// A secret scalar value representing a signer's share of the group secret.
pub const SigningShare = struct {
    scalar: Scalar,

    pub fn fromScalar(scalar: Scalar) SigningShare {
        return SigningShare{ .scalar = scalar };
    }

    pub fn toScalar(self: SigningShare) Scalar {
        return self.scalar;
    }

    pub fn serialize(self: SigningShare) [32]u8 {
        return field.scalarSerialize(self.scalar);
    }

    pub fn deserialize(bytes: [32]u8) !SigningShare {
        const s = try field.scalarDeserialize(bytes);
        return SigningShare{ .scalar = s };
    }
};

/// A public group element representing a single signer's verification share.
pub const VerifyingShare = struct {
    element: Element,

    pub fn fromElement(element: Element) VerifyingShare {
        return VerifyingShare{ .element = element };
    }

    pub fn toElement(self: VerifyingShare) Element {
        return self.element;
    }

    pub fn serialize(self: VerifyingShare) ![33]u8 {
        return group.elementSerialize(self.element);
    }

    pub fn deserialize(bytes: [33]u8) !VerifyingShare {
        const e = try group.elementDeserialize(bytes);
        return VerifyingShare{ .element = e };
    }

    pub fn fromSigningShare(signing_share: SigningShare) VerifyingShare {
        const element = group.elementScalarBaseMul(signing_share.scalar);
        return VerifyingShare{ .element = element };
    }

    /// Compute the public verification share Y_i = ∏_k φ_k^{i^k} from a group
    /// commitment (the sum of all participants' DKG commitments).
    pub fn fromCommitment(identifier: Identifier, commitment: VerifiableSecretSharingCommitment) VerifyingShare {
        return VerifyingShare{ .element = evaluateVss(identifier, commitment) };
    }
};

/// Commitment to one coefficient of the secret polynomial.
pub const CoefficientCommitment = struct {
    element: Element,

    pub fn fromElement(element: Element) CoefficientCommitment {
        return CoefficientCommitment{ .element = element };
    }

    pub fn value(self: CoefficientCommitment) Element {
        return self.element;
    }

    pub fn serialize(self: CoefficientCommitment) ![33]u8 {
        return group.elementSerialize(self.element);
    }

    pub fn deserialize(bytes: [33]u8) !CoefficientCommitment {
        const e = try group.elementDeserialize(bytes);
        return CoefficientCommitment{ .element = e };
    }
};

/// Verifiable secret sharing commitment (coefficient commitments).
pub const VerifiableSecretSharingCommitment = struct {
    coefficients: []const CoefficientCommitment,

    pub fn init(coefficients: []const CoefficientCommitment) VerifiableSecretSharingCommitment {
        return VerifiableSecretSharingCommitment{ .coefficients = coefficients };
    }

    pub fn minSigners(self: VerifiableSecretSharingCommitment) u16 {
        return @intCast(self.coefficients.len);
    }

    pub fn verifyingKey(self: VerifiableSecretSharingCommitment) !VerifyingKey {
        if (self.coefficients.len == 0) return FrostError.MissingCommitment;
        return VerifyingKey.fromElement(self.coefficients[0].value());
    }
};

/// A secret share generated by a trusted dealer.
pub const SecretShare = struct {
    identifier: Identifier,
    signing_share: SigningShare,
    commitment: VerifiableSecretSharingCommitment,

    pub fn verify(self: SecretShare) !struct { VerifyingShare, VerifyingKey } {
        const f_result = group.elementScalarBaseMul(self.signing_share.toScalar());
        const result = evaluateVss(self.identifier, self.commitment);
        if (!group.elementEql(f_result, result)) {
            return FrostError.InvalidSecretShare;
        }
        const verifying_share = VerifyingShare.fromElement(result);
        const verifying_key = try self.commitment.verifyingKey();
        return .{ verifying_share, verifying_key };
    }
};

/// A FROST keypair for a participant.
pub const KeyPackage = struct {
    identifier: Identifier,
    signing_share: SigningShare,
    verifying_share: VerifyingShare,
    verifying_key: VerifyingKey,
    min_signers: u16,

    pub fn fromSecretShare(secret_share: SecretShare) !KeyPackage {
        const vs, const vk = try secret_share.verify();
        return KeyPackage{
            .identifier = secret_share.identifier,
            .signing_share = secret_share.signing_share,
            .verifying_share = vs,
            .verifying_key = vk,
            .min_signers = secret_share.commitment.minSigners(),
        };
    }
};

/// Public data containing all signers' verifying shares and the group key.
pub const PublicKeyPackage = struct {
    verifying_shares: std.AutoHashMap(Identifier, VerifyingShare),
    verifying_key: VerifyingKey,
    min_signers: ?u16,

    pub fn maxSigners(self: PublicKeyPackage) u16 {
        return @intCast(self.verifying_shares.count());
    }

    /// Build the public key package from the DKG commitments of all
    /// participants (each mapped by their identifier). The group verifying
    /// key is the sum of every participant's first commitment, and each
    /// verifying share is derived by evaluating the summed commitment.
    pub fn fromDkgCommitments(
        allocator: std.mem.Allocator,
        commitments: *const std.AutoHashMap(Identifier, *const VerifiableSecretSharingCommitment),
    ) !PublicKeyPackage {
        var ids = std.ArrayList(Identifier).empty;
        defer ids.deinit(allocator);
        var it = commitments.keyIterator();
        while (it.next()) |id| {
            try ids.append(allocator, id.*);
        }
        std.mem.sort(Identifier, ids.items, {}, idLessThan);

        var commit_list = std.ArrayList(VerifiableSecretSharingCommitment).empty;
        defer commit_list.deinit(allocator);
        for (ids.items) |id| {
            try commit_list.append(allocator, commitments.get(id).?.*);
        }
        const group_commitment = try sumCommitments(commit_list.items);
        defer std.heap.page_allocator.free(group_commitment.coefficients);

        var verifying_shares = std.AutoHashMap(Identifier, VerifyingShare).init(allocator);
        errdefer verifying_shares.deinit();
        for (ids.items) |id| {
            try verifying_shares.put(id, VerifyingShare.fromCommitment(id, group_commitment));
        }
        return PublicKeyPackage{
            .verifying_shares = verifying_shares,
            .verifying_key = try group_commitment.verifyingKey(),
            .min_signers = group_commitment.minSigners(),
        };
    }
};

fn idLessThan(_: void, a: Identifier, b: Identifier) bool {
    return a.lessThan(b);
}

/// Sum the coefficient commitments from all participants into one group
/// commitment. Each coefficient position is added element-wise.
pub fn sumCommitments(commitments: []const VerifiableSecretSharingCommitment) !VerifiableSecretSharingCommitment {
    if (commitments.len == 0) return FrostError.IncorrectNumberOfCommitments;
    const degree = commitments[0].coefficients.len;
    var summed = std.heap.page_allocator.alloc(CoefficientCommitment, degree) catch return FrostError.RandomnessError;
    for (0..degree) |k| {
        var acc = group.identity();
        for (commitments) |comm| {
            if (comm.coefficients.len != degree) return FrostError.IncorrectNumberOfCommitments;
            acc = group.elementAdd(acc, comm.coefficients[k].value());
        }
        summed[k] = CoefficientCommitment.fromElement(acc);
    }
    return VerifiableSecretSharingCommitment.init(summed);
}

/// A signing key (the group secret).
pub const SigningKey = struct {
    scalar: Scalar,

    pub fn generate() SigningKey {
        var bytes: [32]u8 = undefined;
        field.randomBytes(&bytes);
        const s = Secp256k1.scalar.Scalar.fromBytes(bytes, .big) catch Secp256k1.scalar.Scalar.zero;
        // Ensure non-zero
        if (s.isZero()) {
            bytes[31] = 1;
        }
        const scalar = Secp256k1.scalar.Scalar.fromBytes(bytes, .big) catch Secp256k1.scalar.Scalar.zero;
        return SigningKey{ .scalar = scalar };
    }

    pub fn fromScalar(scalar: Scalar) !SigningKey {
        if (scalar.isZero()) return FrostError.MalformedSigningKey;
        return SigningKey{ .scalar = scalar };
    }

    pub fn toScalar(self: SigningKey) Scalar {
        return self.scalar;
    }

    pub fn serialize(self: SigningKey) [32]u8 {
        return field.scalarSerialize(self.scalar);
    }

    pub fn deserialize(bytes: [32]u8) !SigningKey {
        const s = try field.scalarDeserialize(bytes);
        return fromScalar(s);
    }

    pub fn sign(self: SigningKey, message: []const u8) !Signature {
        const public = VerifyingKey.fromSigningKey(self);
        const k = field.scalarRandom();
        const R = group.elementScalarBaseMul(k);
        const c = try challenge(&R, &public, message);
        const z = k.add(c.mul(self.scalar));
        return Signature{ .R = R, .z = z };
    }
};

/// A verifying key (group public key).
pub const VerifyingKey = struct {
    element: Element,

    pub fn fromElement(element: Element) VerifyingKey {
        return VerifyingKey{ .element = element };
    }

    pub fn fromSigningKey(signing_key: SigningKey) VerifyingKey {
        return VerifyingKey{ .element = group.elementScalarBaseMul(signing_key.scalar) };
    }

    pub fn toElement(self: VerifyingKey) Element {
        return self.element;
    }

    pub fn serialize(self: VerifyingKey) ![33]u8 {
        return group.elementSerialize(self.element);
    }

    pub fn deserialize(bytes: [33]u8) !VerifyingKey {
        const e = try group.elementDeserialize(bytes);
        return VerifyingKey{ .element = e };
    }

    pub fn verify(self: VerifyingKey, message: []const u8, signature: Signature) !void {
        const zB = group.elementScalarBaseMul(signature.z);
        const cA = group.elementScalarMul(self.element, try challenge(&signature.R, &self, message));
        const check = group.elementSub(zB, group.elementAdd(cA, signature.R));
        if (!group.elementIsIdentity(check)) {
            return FrostError.InvalidSignature;
        }
    }

    pub fn fromCommitment(commitment: VerifiableSecretSharingCommitment) !VerifyingKey {
        return commitment.verifyingKey();
    }
};

/// Compute Schnorr challenge.
pub fn challenge(R: *const Element, verifying_key: *const VerifyingKey, msg: []const u8) !Scalar {
    const r_bytes = group.elementSerialize(R.*) catch @as([33]u8, @splat(0));
    const vk_bytes = group.elementSerialize(verifying_key.element) catch @as([33]u8, @splat(0));
    var preimage = std.ArrayList(u8).empty;
    defer preimage.deinit(std.heap.page_allocator);
    try preimage.appendSlice(std.heap.page_allocator, &r_bytes);
    try preimage.appendSlice(std.heap.page_allocator, &vk_bytes);
    try preimage.appendSlice(std.heap.page_allocator, msg);
    return cs.H2(preimage.items);
}

/// Evaluate polynomial at identifier using Horner's method.
pub fn evaluatePolynomial(identifier: Identifier, coefficients: []const Scalar) Scalar {
    var value = field.scalarZero();
    const id_scalar = field.scalarDeserialize(identifier.serialize()) catch field.scalarZero();
    var i: usize = coefficients.len;
    while (i > 1) {
        i -= 1;
        value = field.scalarAdd(value, coefficients[i]);
        value = field.scalarMul(value, id_scalar);
    }
    value = field.scalarAdd(value, coefficients[0]);
    return value;
}

/// Evaluate VSS verification equation.
pub fn evaluateVss(identifier: Identifier, commitment: VerifiableSecretSharingCommitment) Element {
    const id_scalar = field.scalarDeserialize(identifier.serialize()) catch field.scalarZero();
    var i_to_the_k = field.scalarOne();
    var sum = group.identity();
    for (commitment.coefficients) |comm| {
        sum = group.elementAdd(sum, group.elementScalarMul(comm.value(), i_to_the_k));
        i_to_the_k = field.scalarMul(i_to_the_k, id_scalar);
    }
    return sum;
}

/// Generate random polynomial coefficients.
pub fn generateCoefficients(min_signers: u16) []Scalar {
    var coeffs = std.heap.page_allocator.alloc(Scalar, min_signers) catch return &[_]Scalar{};
    for (0..min_signers) |i| {
        coeffs[i] = field.scalarRandom();
    }
    return coeffs;
}

/// Generate secret polynomial and commitment.
pub fn generateSecretPolynomial(secret: SigningKey, max_signers: u16, min_signers: u16, coefficients: []Scalar) !struct { []Scalar, VerifiableSecretSharingCommitment } {
    if (min_signers < 2 or max_signers < 2 or min_signers > max_signers) {
        return FrostError.InvalidMinSigners;
    }
    if (coefficients.len != min_signers - 1) {
        return FrostError.InvalidCoefficient;
    }
    var all_coeffs = std.heap.page_allocator.alloc(Scalar, min_signers) catch return FrostError.RandomnessError;
    all_coeffs[0] = secret.scalar;
    @memcpy(all_coeffs[1..], coefficients);
    var commitment_coeffs = std.heap.page_allocator.alloc(CoefficientCommitment, min_signers) catch return FrostError.RandomnessError;
    for (all_coeffs, 0..) |c, i| {
        commitment_coeffs[i] = CoefficientCommitment.fromElement(group.elementScalarBaseMul(c));
    }
    return .{ all_coeffs, VerifiableSecretSharingCommitment.init(commitment_coeffs) };
}

/// Generate secret shares.
fn generateSecretShares(secret: SigningKey, max_signers: u16, min_signers: u16, coefficients: []Scalar, identifiers: []const Identifier) ![]SecretShare {
    const all_coeffs, const commitment = try generateSecretPolynomial(secret, max_signers, min_signers, coefficients);
    var shares = std.heap.page_allocator.alloc(SecretShare, max_signers) catch return FrostError.RandomnessError;
    for (identifiers, 0..) |id, i| {
        const signing_share = SigningShare.fromScalar(evaluatePolynomial(id, all_coeffs));
        shares[i] = SecretShare{
            .identifier = id,
            .signing_share = signing_share,
            .commitment = commitment,
        };
    }
    return shares;
}

/// Default identifiers (1 to max_signers).
pub fn defaultIdentifiers(max_signers: u16) ![]Identifier {
    var ids = std.heap.page_allocator.alloc(Identifier, max_signers) catch return FrostError.RandomnessError;
    for (1..max_signers + 1) |i| {
        ids[i - 1] = try Identifier.fromU16(@intCast(i));
    }
    return ids;
}

/// Trusted dealer key generation.
pub fn generateWithDealer(max_signers: u16, min_signers: u16, identifiers: []const Identifier) !struct { []SecretShare, PublicKeyPackage } {
    const key = SigningKey.generate();
    return try split(&key, max_signers, min_signers, identifiers);
}

/// Split an existing key into FROST shares.
pub fn split(secret: *const SigningKey, max_signers: u16, min_signers: u16, identifiers: []const Identifier) !struct { []SecretShare, PublicKeyPackage } {
    if (min_signers < 2 or max_signers < 2 or min_signers > max_signers) {
        return FrostError.InvalidMinSigners;
    }
    if (identifiers.len != max_signers) {
        return FrostError.IncorrectNumberOfIdentifiers;
    }
    // Check for duplicates
    for (identifiers, 0..) |id1, i| {
        for (identifiers[i + 1 ..]) |id2| {
            if (id1.eql(id2)) return FrostError.DuplicatedIdentifier;
        }
    }
    const coefficients = generateCoefficients(min_signers - 1);
    const shares = try generateSecretShares(secret.*, max_signers, min_signers, coefficients, identifiers);
    const verifying_key = VerifyingKey.fromSigningKey(secret.*);
    var verifying_shares = std.AutoHashMap(Identifier, VerifyingShare).init(std.heap.page_allocator);
    for (shares) |share| {
        const vs = VerifyingShare.fromSigningShare(share.signing_share);
        try verifying_shares.put(share.identifier, vs);
    }
    const pubkey_package = PublicKeyPackage{
        .verifying_shares = verifying_shares,
        .verifying_key = verifying_key,
        .min_signers = min_signers,
    };
    return .{ shares, pubkey_package };
}

/// Reconstruct secret from key packages using Lagrange interpolation.
pub fn reconstruct(key_packages: []const KeyPackage) !SigningKey {
    if (key_packages.len == 0) return FrostError.IncorrectNumberOfShares;
    var min_signers: u16 = key_packages[0].min_signers;
    for (key_packages) |kp| {
        if (kp.min_signers < min_signers) min_signers = kp.min_signers;
    }
    if (key_packages.len < min_signers) return FrostError.IncorrectNumberOfShares;
    var secret = field.scalarZero();
    for (key_packages) |kp| {
        const lambda = try deriveInterpolatingValue(kp.identifier, key_packages);
        secret = field.scalarAdd(secret, field.scalarMul(lambda, kp.signing_share.toScalar()));
    }
    return SigningKey.fromScalar(secret);
}

/// Compute Lagrange coefficient.
pub fn deriveInterpolatingValue(signer_id: Identifier, key_packages: []const KeyPackage) !Scalar {
    var ids = std.ArrayList(Identifier).empty;
    defer ids.deinit(std.heap.page_allocator);
    for (key_packages) |kp| {
        try ids.append(std.heap.page_allocator, kp.identifier);
    }
    return computeLagrangeCoefficient(ids.items, signer_id);
}

/// Compute Lagrange coefficient for a set of identifiers.
pub fn computeLagrangeCoefficient(identifiers: []const Identifier, x_i: Identifier) !Scalar {
    if (identifiers.len == 0) return FrostError.IncorrectNumberOfIdentifiers;
    var num = field.scalarOne();
    var den = field.scalarOne();
    var x_i_found = false;
    const x_i_scalar = field.scalarDeserialize(x_i.serialize()) catch field.scalarZero();
    for (identifiers) |x_j| {
        if (x_i.eql(x_j)) {
            x_i_found = true;
            continue;
        }
        const x_j_scalar = field.scalarDeserialize(x_j.serialize()) catch field.scalarZero();
        num = field.scalarMul(num, x_j_scalar);
        den = field.scalarMul(den, field.scalarSub(x_j_scalar, x_i_scalar));
    }
    if (!x_i_found) return FrostError.UnknownIdentifier;
    const den_inv = try field.scalarInvert(den);
    return field.scalarMul(num, den_inv);
}
